// ~/ecosystem.dev.config.cjs

module.exports = {
  apps: [
    {
      name: 'demo_workday_tracker',
      port: '3000',
      exec_mode: 'cluster',
      instances: '2',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      error_file: 'logs/dev/02_demo_instance.error.log',
      out_file: 'logs/dev/02_demo_instance.output.log',
      merge_logs: true,
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm Z",
      // autorestart: true,
      max_restarts: 10,
      env: {
        NUXT_PUBLIC_ENVIRONMENT: 'production',
        NUXT_PUBLIC_SOCKET_NAMESPACE: '/demo',
        NUXT_LOGIN_USERNAME: 'demo',
        NUXT_LOGIN_PASSWORD: 'demo',
        NUXT_PUBLIC_LOGIN_NAME: 'Demo',
      },
    },
    {
      name: 'lupine_workday_tracker',
      port: '3001',
      exec_mode: 'cluster',
      instances: '2',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      error_file: 'logs/dev/01_my_instance.error.log',
      out_file: 'logs/dev/01_my_instance.output.log',
      merge_logs: true,
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm Z",
      // autorestart: true,
      max_restarts: 10,
      env: {
        NUXT_PUBLIC_ENVIRONMENT: 'production',
        NUXT_PUBLIC_SOCKET_NAMESPACE: '/lupine',
        NUXT_LOGIN_USERNAME: 'lupine',
        NUXT_LOGIN_PASSWORD: 'lupine',
        NUXT_PUBLIC_LOGIN_NAME: 'Lupine',
      },
    },
    {
      name: 'test_workday_tracker',
      port: '3002',
      exec_mode: 'cluster',
      instances: '2',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      error_file: 'logs/dev/03_test_instance.error.log',
      out_file: 'logs/dev/03_test_instance.output.log',
      merge_logs: true,
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm Z",
      // autorestart: true,
      max_restarts: 10,
      env: {
        NUXT_PUBLIC_ENVIRONMENT: 'production',
        NUXT_PUBLIC_SOCKET_NAMESPACE: '/test',
        NUXT_LOGIN_USERNAME: 'test',
        NUXT_LOGIN_PASSWORD: 'test',
        NUXT_PUBLIC_LOGIN_NAME: 'Test',
      },
    },
  ],
};
