// ~/ecosystem.prod.config.cjs

module.exports = {
  apps: [
    {
      name: 'demo_workday_tracker',
      port: '3000',
      exec_mode: 'cluster',
      instances: '2',
      script: '.output/server/index.mjs',
      error_file: 'logs/prod/02_demo_instance.error.log',
      out_file: 'logs/prod/02_demo_instance.output.log',
      merge_logs: true,
      log_date_format: "MM-DD HH:mm",
      autorestart: true,
      max_restarts: 10,
      env: {
        NUXT_PUBLIC_ENVIRONMENT: 'production',
        NUXT_PUBLIC_SOCKET_NAMESPACE: '/demo',
        NUXT_LOGIN_USERNAME: 'demo',
        NUXT_LOGIN_PASSWORD: 'ReasonableSecurity',
        NUXT_PUBLIC_LOGIN_NAME: 'Demo',
      },
    },
    {
      name: 'lupine_workday_tracker',
      port: '3001',
      exec_mode: 'cluster',
      instances: '2',
      script: '.output/server/index.mjs',
      error_file: 'logs/prod/01_my_instance.error.log',
      out_file: 'logs/prod/01_my_instance.output.log',
      merge_logs: true,
      log_date_format: "MM-DD HH:mm",
      autorestart: true,
      max_restarts: 10,
      env: {
        NUXT_PUBLIC_ENVIRONMENT: 'production',
        NUXT_PUBLIC_SOCKET_NAMESPACE: '/lupine',
        NUXT_LOGIN_USERNAME: 'lupine',
        NUXT_LOGIN_PASSWORD: 'F0xg1ove&Lupin3',
        NUXT_PUBLIC_LOGIN_NAME: 'Lupine',
      },
    },
    {
      name: 'test_workday_tracker',
      port: '3002',
      exec_mode: 'cluster',
      instances: '2',
      script: '.output/server/index.mjs',
      error_file: 'logs/prod/03_test_instance.error.log',
      out_file: 'logs/prod/03_test_instance.output.log',
      merge_logs: true,
      log_date_format: "MM-DD HH:mm",
      autorestart: true,
      max_restarts: 10,
      env: {
        NUXT_PUBLIC_ENVIRONMENT: 'production',
        NUXT_PUBLIC_SOCKET_NAMESPACE: '/test',
        NUXT_LOGIN_USERNAME: 'test',
        NUXT_LOGIN_PASSWORD: 'Lup1n3&Hyacinth',
        NUXT_PUBLIC_LOGIN_NAME: 'Test',
      },
    },
  ],
};
