# PowerShell script to generate VAPID keys and append to .env file
# to run, type `. .\generateVapidKeys.ps1` in the terminal

# NOTE: this script will not detect if the keys already exist in the .env, 
# and will always append new keys when it is run.

# Generate VAPID keys using web-push
Write-Host "Generating VAPID keys..."
$vapidKeysOutput = npx web-push generate-vapid-keys --yes

# Check if the command was successful (optional, but good practice)
if ($LASTEXITCODE -ne 0) {
    Write-Error "Error generating VAPID keys. Please ensure you have web-push installed (npm install web-push -g or npm install web-push --save-dev)."
    exit 1
}

# Parse the output to extract public and private keys
# The output format is typically:
# VAPID public key: <publicKey>
# VAPID private key: <privateKey>

$publicKeyMatch = Select-String -InputObject $vapidKeysOutput -Pattern 'Public Key: (.*)'
$privateKeyMatch = Select-String -InputObject $vapidKeysOutput -Pattern 'Private Key: (.*)'

if ($publicKeyMatch -and $privateKeyMatch) {
    $publicKey = $publicKeyMatch.Matches[0].Groups[1].Value.Trim()
    $privateKey = $privateKeyMatch.Matches[0].Groups[1].Value.Trim()

    Write-Host "VAPID keys generated successfully."

    # Construct the lines to append to the .env file
    $commentLine = "# these variables autogenerated by generateVapidKeys.ps1"
    $publicKeyLine = "VAPID_PUBLIC_KEY='$publicKey'"
    $privateKeyLine = "VAPID_PRIVATE_KEY='$privateKey'"

    # Define the .env file path (you can adjust this if needed)
    $envFilePath = ".env"

    # Check if .env file exists, if not, create it
    if (!(Test-Path -Path $envFilePath)) {
        Write-Host "Creating .env file..."
        New-Item -ItemType File -Path $envFilePath -Force | Out-Null
    }

    # Append the keys to the .env file
    Write-Host "Appending keys to .env file..."
    Add-Content -Path $envFilePath -Value (($commentLine, $publicKeyLine, $privateKeyLine) -join "`r`n")

    Write-Host "VAPID keys appended to '$envFilePath'."
    Write-Host "Make sure to add '$envFilePath' to your .gitignore file if you haven't already."
} else {
    Write-Error "Failed to parse VAPID keys from output."
    Write-Error "Output was: $($vapidKeysOutput)"
    exit 1
}

Write-Host "Script completed."